---
# task install

# Selinux
- name: disable selinux
  selinux:
    state: disabled

# Firewalld configuration if eoa_firewalld is true
- name: start and enable firewalld
  service:
    name: firewalld
    state: started
    enabled: yes
  when: eoa_firewalld

# Enable HTTPS service
- name: open https
  firewalld:
    service: https
    permanent: true
    immediate: true
    state: enabled

# Prerequisites
- name: install epel repo
  yum:
    name: epel-release
    state: latest
  
- name: install prerequisites
  yum:
    name: ['python-virtualenv', 'tar', 'unzip']
    state: latest

# Browsers installation
- name: install google64 repo
  yum_repository:
    name: google64
    description: Google - x86_64
    baseurl: http://dl.google.com/linux/rpm/stable/x86_64
    enabled: yes
    gpgcheck: yes
    gpgkey: https://dl-ssl.google.com/linux/linux_signing_key.pub
    file: google-x86_64 

- name: install firefox and google-chrome-stable
  yum:
    name: ['firefox', 'google-chrome-stable']
    state: latest

# Virtualenv configuration
- name: add the user 'eoa' and creates its home directory
  user:
    name: "{{ eoa_user }}"
    comment: EyesOfApplication user
    home: "{{ eoa_dir }}"

- name: check virtualenv directory
  file:
    path: "{{ eoa_dir_venv }}"
    state: directory
  become_user: "{{ eoa_user }}"

# Pip installation
- name: check pip is the latest version
  pip:
    name: pip
    state: latest
    virtualenv_site_packages: yes
    virtualenv: "{{ eoa_dir_venv }}"
    umask: "0022"
  register: _pip
  become_user: "{{ eoa_user }}"

- name: check python prerequisites are installed
  pip:
    name: ['coloredlogs', 'cryptography', 'PyYAML', 'validators', 'oyaml', 'ruamel.yaml']
    state: latest
    virtualenv: "{{ eoa_dir_venv }}"
    umask: "0022"
  become_user: "{{ eoa_user }}"

# Selenium installation
- name: check selenium is installed
  pip:
    name: selenium
    state: latest
    virtualenv: "{{ eoa_dir_venv }}"
    umask: "0022"
  become_user: "{{ eoa_user }}"

- name: download selenium drivers
  get_url: 
    url: "{{ item }}"
    dest: /tmp
  with_items:
    - "https://github.com/mozilla/geckodriver/releases/download/v{{eoa_firefox_version}}/geckodriver-v{{eoa_firefox_version}}-linux64.tar.gz"  
    - "https://chromedriver.storage.googleapis.com/{{eoa_chrome_version}}/chromedriver_linux64.zip"
  
- name : unarchive selenium drivers 
  unarchive:
    src: "/tmp/{{ item }}" 
    dest: "{{ eoa_dir_venv }}/bin"
    owner: "{{ eoa_user }}"
    group: "{{ eoa_user }}"
    remote_src: yes
  with_items:
    - "geckodriver-v{{ eoa_firefox_version }}-linux64.tar.gz"
    - "chromedriver_linux64.zip"

# Installing EOA
- name: clone eyesofapplication project from gitlab
  become: false
  local_action:
    module: git
    repo: "{{ eoa_saas_git_url }}"
    version: "{{ eoa_git_version }}"
    dest: "{{ eoa_git_dir }}"
    update: yes
    force: yes
    accept_hostkey: yes
  run_once: yes

- name: install files
  synchronize:
    src: "{{ eoa_git_dir}}/"
    dest: "{{ eoa_dir }}/"
    archive: no
    recursive: yes
    rsync_opts:
      - "--exclude=conf/eoa.yml"

- name: check if eoa.yml is installed
  stat:
    path: /srv/eyesofapplication/conf/eoa.yml
  register: stat_result

- name: install eoa.yml if not installed
  synchronize:
    src: "{{ eoa_git_dir}}/"
    dest: "{{ eoa_dir }}/"
    archive: no
    recursive: yes
  when: stat_result.stat.exists == False

- name: set owner and group
  file:
    path: "{{ eoa_dir }}"
    owner: "{{ eoa_user }}"
    group: "{{ eoa_user }}"
    recurse: yes

# Configure sudo access if eon
- name: set sudo access for nagios user
  lineinfile:
    path: /etc/sudoers
    state: present
    line: 'nagios ALL=NOPASSWD:{{eoa_dir}}/bin/eoa.py'
    validate: '/usr/sbin/visudo -cf %s'
  when: eoa_is_eon